name: Cypress + Allure

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write      # for GitHub Pages
  id-token: write   # for GitHub Pages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean allure (just in case)
        run: npx rimraf allure-results allure-report

      # ---- Run tests ----
      - name: Run Component tests (CT)
        run: npm run test:ct

      - name: Run E2E tests
        run: npm run test:e2e

      # ---- Build Allure report ----
      - name: Generate Allure report
        run: npm run allure:generate

      # ---- Upload artifacts to the run ----
      - name: Upload Allure HTML
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

  # ---- OPTIONAL: Publish Allure to GitHub Pages ----
  publish-pages:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
